_BASE_: ../coco-stuff-164k-171/mask2former_R50_bs32_60k.yaml
ORACLE: True
MODEL:
  WEIGHTS: ""
  META_ARCHITECTURE: "ProposalClipClassifier"
  MASK_ON: True
  CLIP_ADAPTER:
    PROMPT_LEARNER: "learnable"
    PROMPT_DIM: 512
    PROMPT_SHAPE: (16, 0)
    CLIP_MODEL_NAME: "ViT-B/16"
DATASETS:
  TRAIN: ("coco_2017_train_full_task_base_classification",)  # coco_2017_train_full_task_base_classification "coco_2017_train_stuff_base_sem_seg_classification",
  TEST: ("coco_2017_test_stuff_sem_seg_classification",)
  SAMPLE_PER_CLASS: 64 
INPUT:
  MIN_SIZE_TRAIN: (224,244)
  MIN_SIZE_TEST: 224
  MAX_SIZE_TEST: 2560
  SIZE_DIVISIBILITY: -1
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "mask_former_full_binary_semantic"
  TASK_NAME: ["semantic segmentation.",  "instance segmentation.",  "panoptic segmentation."]
SOLVER:
  OPTIMIZER: "SGD"
  BASE_LR: 0.02
  WEIGHT_DECAY: 0.001
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  WARMUP_METHOD: "constant"  
  WARMUP_FACTOR: 0.005
  WARMUP_ITERS: 100
  IMS_PER_BATCH: 32
  TEST_IMS_PER_BATCH: 4
  MAX_ITER: 16000
  CHECKPOINT_PERIOD: 2000
TEST:
  EVAL_PERIOD: 2000